# Generated by Django 5.0.7 on 2024-12-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0002_alter_passenger_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passenger",
            name="university_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="الكود الجامعي",
            ),
        ),
    ]
