# Generated by Django 5.0.7 on 2024-12-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0003_alter_passenger_university_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="route",
            field=models.TextField(
                default="", help_text="أدخل كل خط في سطر جديد.", verbose_name="الطريق"
            ),
        ),
    ]
