# Generated by Django 5.0.7 on 2024-12-23 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0004_alter_trip_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="selected_route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Anaconda_bus_APP.route",
                verbose_name="الخط المختار",
            ),
        ),
    ]
