# Generated by Django 5.0.7 on 2024-12-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0005_booking_selected_route"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="selected_route",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
