# Generated by Django 5.0.7 on 2024-12-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0006_alter_booking_selected_route"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="driver_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="رقم السائق"
            ),
        ),
    ]
