# Generated by Django 5.0.7 on 2024-12-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0008_booking_seat_one_way_booking_seat_return_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seat_one_way",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="seat_return",
        ),
    ]
