# Generated by Django 5.0.7 on 2024-12-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Anaconda_bus_APP", "0009_remove_booking_seat_one_way_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "نشط"),
                    ("completed", "مكتمل"),
                    ("cancelled", "ملغي"),
                    ("prepaid", "مدفوع مسبقًا"),
                ],
                default="active",
                max_length=20,
                verbose_name="حاله الدفع",
            ),
        ),
    ]
